apiVersion: v1
kind: ConfigMap
metadata:
  #name: postgres-10.7-conf
  name: pg-config
  namespace: spark
data:
  postgres.conf: |2    
    listen_addresses = '*'
    shared_buffers = 128MB

  primary_init_script.sh: |
    #!/bin/bash
    set -e

    # This script assumes that the env-var $POSTGRES_MY_DB_PASSWORD contains the password of the custom user to create.
    # You can add any env-var in your Kubegres resource config YAML.

    dt=$(date '+%d/%m/%Y %H:%M:%S');
    echo "$dt - Running init script the 1st time Primary PostgreSql container is created...";

    customDatabaseName="lighter"
    customUserName="lighter"

    echo "$dt - Running: psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB ...";

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $customDatabaseName;
    CREATE USER $customUserName WITH PASSWORD '$POSTGRES_MY_DB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE "$customDatabaseName" to $customUserName;
    EOSQL

    echo "$dt - Init script is completed";


  copy_primary_data_to_replica.sh: |
    #!/bin/bash
    set -e
    echo "no replication configured as this isn't supported for Postgres versions < 12.4"
  primary_create_replication_role.sh: |
    #!/bin/bash
    set -e
    echo "no replication configured as this isn't supported for Postgres versions < 12.4"
  promote_replica_to_primary.sh: |
    #!/bin/bash
    set -e
    echo "skipping adding replicas since this isn't supported for Postgres versions < 12.4"