apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
  namespace: spark
spec:
   replicas: 1
   image: postgres:14.1
   failover:
      isDisabled: true
   customConfig: pg-config
   database:
      size: 100Mi
   env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pg-secret
          key: superUserPassword
    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pg-secret
          key: replicationUserPassword