---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: datahub
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/datahub
  prune: true
  validation: client 
  patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: "datahub"
      namespace: "flux-system"
    patch: |-
      - op: replace
        path: "/spec/values/datahub-frontend/ingress/hosts/0/host"
        value: catalog.sc02.core.neosdata.io
      - op: replace
        path: "/spec/values/datahub-frontend/ingress/tls/0/hosts/0"
        value: catalog.sc02.core.neosdata.io