apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: oci
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/oci
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sources
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/sources
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: spark-operator
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/spark-operator
  prune: true
  validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: postgres
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/postgres
#   prune: true
#   validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: lighter
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/lighter
#   prune: true
#   validation: client

# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: mysql
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/mysql
#   prune: true
#   validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: mongodb
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/mongodb
#   prune: true
#   validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kong
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/kong
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kafka
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/kafka
  prune: true
  validation: client  
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: datahub
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/datahub
  prune: true
  validation: client  
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/cert-manager
  prune: true
  validation: client  
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/sealed-secrets
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/external-dns
  prune: true
  validation: client  
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: common-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/secrets
  prune: true
  validation: client  
 
