apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secrets
  namespace: datahub
spec:
  encryptedData:
    mysql-root-password: AgCkv/nsMNS9n7Y8XROAI7YK8xCoW1mTt3Jyikh3ou3ochLW40m77+5fR5+jus3UoxYf1yoVpkVlzCOHHHP8oMqoYVd8/20R+EfgMJg0AzAYGIoWLMWxwcQf0IHJLepBo0gxGNpHx9pYk5Y2HOkH+DpMmWMinXvrnWWpXAAbEQpH8Gzp10R0uH3eNIywvHPauZs5WJr54Jb1ljWbzADnHOyCCZAbXC1bbjG9WOKhWi8y0fB3iDQgJLVfxYaoMgPc8++sUNojpkysYOKt6Gg7jQahhECPh4rzKHI3WXkAStlfZDlkJmtAKRU1Da/BIRAjf3Qgt3TBMJqCnWqcIZ4X6BS/IGJUoCNy627mzsFvlY3hGPTgwprP08Ud8lxFW3lH916dKHvOBm7TTe3KFl1W4QJz9OT2Z7XBe75G5VXrVqIRmkDSVeajOpBALJdYO73tv+ho78DkJiHrL2xrhV8wGUg5F5gR3McplQDL8uNXBVfmHrZYJygqfkblYcza6ZzmZoOqIi6/UySB91nbTbeBeEiKWvV1plaHNYugrdZszI+oXis1iV6SGIC1R88dDq9TT0Od9QBZhdpqLIgvVg4ZtXgDV02rF/AoD2lvKgDnW7jy+4zo1ESChEJzP4dNUuIbXliiqDeyu/HndcwT91//LlJfZcMi8IGDmlGvjj+jiP9PKKlssAlwKbXThCXb2iZ75PtycokSX2oEXLlGg+oGMmf7zZg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-secrets
      namespace: datahub
    type: Opaque

