apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: neo4j-secrets
  namespace: datahub
spec:
  encryptedData:
    neo4j-password: AgB8HUjgmX0ooHtpWpq5+id9p5ou/ZSJIWERJ08lWMQdAQpARodZdx6gKlItIeA/UO3PE6lYUMBST0PVwgdkpCwNmakH/ubzXW8BN+Li7WpS8Fs+ZpJOVHdED4HLJAlCBAuzxKBj72UvBt9RmEYotrEsfRjGLwQpwFMMPJlrE1I8/Q8OWAp1+HCD7V5fO1Is3PmA7zdlstTthnfrYosaExplmKGuzzcLJrtd0lBCiXWzgTyRMF6+ZCznFn4NaL81k7Ly3RVmsWp8yx/kcDykBVMia+ar2sgKxzCgzuwnXkS9xWNmkpCMeXRXVdVLiua3ctV+DX2QcLUMDpfkK4SQwPbIlQtycPcPPJOOvDmuR8iH40OxeLPaskHOnPJOx1ug1uDRvQ+mAJ/LPG/DL+b7phWUjWDO05KWZA0vu62pQpWd//d73pXl9eliz/5kahAkSE8Y6m6hZ43e6NwpPrsWItiRGPfm0z98VmDb1QER1Cf0E22AKONmBUDQJKe6Mrw9+vW14k4mrf6XvQ4E7VKbTV2sOjB7kDOcO7BYhV9mrUsSwm+RN0k04WXGtzIZN5dFeUGPiEpeVhgZPhza9UDQOkxxh3yFG1AzKQIQj6IqCo7SQYeaSSUFpvDIYjE0QfJDH3uo3mLxwUA57/Z15sgtqGFQRMwJn8/PVjkZFh/VBKHO2RfsaUl65OAIEjmUhwm5oP1G0gf+oIab+M8gLOLyZzGMM2Q=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: neo4j-secrets
      namespace: datahub
    type: Opaque

