apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: flux-system
spec:
  releaseName: kong
  chart:
    spec:
      chart: kong
      version: 2.8.2
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  targetNamespace: kong
  values:
