apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: flux-system
spec:
  releaseName: kong
  chart:
    spec:
      chart: kong
      version: 2.8.2
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 9
  targetNamespace: kong
  values:
    dblessConfig:
      config: |
        # _format_version: "1.1"
        # # this section is not necessary if there's already a route that matches
        # # /.well-known/acme-challenge path with http protocol
        # services:
        #   - name: datahub
        #     url: http://127.0.0.1:65535
        #     routes:
        #       - name: datahub
        #         protocols:
        #           - http
        #         paths:
        #           - /.well-known/acme-challenge