apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flux-system
spec:
  releaseName: mongodb
  chart:
    spec:
      chart: mongodb
      version: 12.1.19
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  targetNamespace: mongodb
  values:

