apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: livy
  namespace: flux-system
spec:
  releaseName: livy
  chart:
    spec:
      chart: livy
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: jahstreet
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 9
  targetNamespace: livy
  values:
    image:
      repository: owainperry/livy-spark
      tag: 0.8.0-incubating-spark_3.3.1_2.12-hadoop_3_cloud
    rbac:
      create: true

