apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
  labels:
    owner: platform   
spec:
  interval: 8h
  url: https://charts.jetstack.io