apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datahub
  namespace: flux-system
spec:
  releaseName: datahub
  chart:
    spec:
      chart: datahub
      version: 0.2.81
      sourceRef:
        kind: HelmRepository
        name: datahub
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 9
  targetNamespace: datahub
  values:
    datahub-frontend:
      service:
        type: "ClusterIP"
      ingress: 
        enabled: true
        annotations:          
          konghq.com/strip-path: "true"
          kubernetes.io/ingress.class: kong
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: sc02.core.neosdata.io
            paths: 
              - /
            #redirectPaths: []
        tls: 
        - secretName: datahub-tls
          hosts:
            - sc02.core.neosdata.io
    datahub-gms:
      service:
        type: "ClusterIP"    
  

