apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datahub-prerequisites
  namespace: flux-system
spec:
  releaseName: datahub
  chart:
    spec:
      chart: datahub-prerequisites
      version: 0.0.6
      sourceRef:
        kind: HelmRepository
        name: datahub
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  targetNamespace: datahub
  values:

  


