apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datahub
  namespace: flux-system
spec:
  releaseName: datahub
  chart:
    spec:
      chart: datahub
      version: 0.2.81
      sourceRef:
        kind: HelmRepository
        name: datahub
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  targetNamespace: datahub
  values:
    datahub-frontend:
      service:
        type: "ClusterIP"
    datahub-gms:
      service:
        type: "ClusterIP"    
  

