apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spark
  namespace: flux-system
spec:
  releaseName: spark
  chart:
    spec:
      chart: spark
      version: 6.1.13
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 9
  targetNamespace: spark
  values:
    worker: 
        replicaCount: 1